# Generated by Django 3.2.8 on 2023-11-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_productosegreso_categorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categorias',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
