# Generated by Django 3.2.8 on 2023-11-11 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_arriendos_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arriendos',
            name='producto',
        ),
    ]
